# Generated by Django 5.2 on 2025-05-03 06:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('maruti_suzuki', 'Maruti Suzuki'), ('tata', 'Tata'), ('mahindra', 'Mahindra'), ('hyundai', 'Hyundai')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('mileage', models.FloatField()),
                ('safety', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('interior', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('car_type', models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('mpv', 'MPV'), ('off-roader', 'Off-Roader')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol/cng', 'Petrol/CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('crash_test_video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit number', regex='^\\d{10}$')])),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.PositiveIntegerField()),
                ('purchase_year', models.PositiveIntegerField()),
                ('expected_price', models.PositiveIntegerField()),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='sell_car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
